# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SelectPropried
                                 A QGIS plugin
 Selecao de propriedades (CAR, Municipio, Cartas Topograficas)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-06-12
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Thomaz Costa
        email                : thomaz.costa@embrapa.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtCore import QSettings, QTranslator, QCoreApplication
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAction, QMainWindow, QPushButton, QToolTip, QLabel, QTextEdit
from qgis.core import *
from qgis.utils import iface

import math
import numpy as np

import grass.script
from osgeo import ogr, osr, gdal

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .select_propried_dialog import SelectPropriedDialog
import os.path

import processing
import os

QgsApplication.instance().arguments()

class SelectPropried:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'SelectPropried_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&SelectPropried')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('SelectPropried', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/select_propried/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'SelectPropried'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&SelectPropried'),
                action)
            self.iface.removeToolBarIcon(action)

    def variaveis(self):
        """define variaveis utilizadas na funcao run"""
        # Variaveis para Declividade
        self.decliv_min = self.dlg.doubleSpinBox.value()
        self.decliv_max = self.dlg.doubleSpinBox_2.value()

        # Variaveis para conversão utm e para tile (Municipios)
        self.zona = self.dlg.spinBox_2.value()
        self.munic = self.dlg.textEdit.toPlainText()

        # Variável para Degr.Past
        self.degrpast = self.dlg.spinBox.value()

        # Variável para Aptidão Agricola Pedoecol CNPS
        self.aptagric = self.dlg.spinBox_3.value()

        # Variável para área mínima (ha)
        self.area_min = self.dlg.spinBox_4.value()

    def ESPG(self):
        if self.zona == 22:
            self.ESPG = 31982
        elif self.zona == 23:
            self.ESPG = 31983
        elif self.zona == 24:
            self.ESPG = 31984
        else:
            print("Digite a zona corretamente! ex. 23")
        return self.ESPG
    
    def lista_param_result (self):

        lista_param = [str(self.decliv_min),str(self.decliv_max),'1',str(self.decliv_max),'60000','0'\
    ,'-33000',str(self.decliv_min),'0']
        return lista_param
            
    def lista_param_result1(self):
        if self.degrpast == 1:
            lista_param = ['1', '2', '1','2', '4', '0']
        elif self.degrpast == 2:
            lista_param = ['1', '2', '0','2', '3', '1','3','4','0']
        elif self.degrpast == 3:
            lista_param = ['1', '3', '0','3','4','1']
        else:
            print("Parametro incorreto! digite 1, 2 ou 3")
        return lista_param

    def lista_param_result2(self):    
            
        if self.aptagric == 1:
            lista_param = ['0', '1', '0', '1', '2', '1','2', '13', '0']
        elif self.aptagric == 2:
            lista_param = ['0', '2', '0','2', '3', '1','3','13','0']
        elif self.aptagric == 3:
            lista_param = ['0', '3', '0','3', '4', '1','4','13','0']
        elif self.aptagric == 4:
            lista_param = ['0', '4', '0','3', '5', '1','5','13','0']
        elif self.aptagric == 5:
            lista_param = ['0', '5', '0','5', '6', '1','6','13','0']
        elif self.aptagric == 6:
            lista_param = ['0', '6', '0','6', '7', '1','7','13','0']
        elif self.aptagric == 7:
            lista_param = ['0', '7', '0','7', '8', '1','8','13','0']
        elif self.aptagric == 8:
            lista_param = ['0', '8', '0','8', '9', '1','9','13','0']
        elif self.aptagric == 9:
            lista_param = ['0', '9', '0','9', '10', '1','10','13','0']
        elif self.aptagric == 10:
            lista_param = ['0', '10', '0','10', '11', '1','11','13','0']
        elif self.aptagric == 11:
            lista_param = ['0', '11', '0','11', '12', '1','12','13','0']
        elif self.aptagric == 12:
            lista_param = ['0', '12', '0','12', '13', '1']

        else: print('Parametro incorreto! digite um número entre 1 e 12')
        return lista_param
    
    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = SelectPropriedDialog()

        # show the dialog
        self.dlg.show()

        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
           # chamando as variaveis
            self.variaveis()

            #-------------------------------------------------------
            # ------------------------------------------------------
            # clas_decliv.py

            # parametros clas_decliv, degr_past, apt_agric
            lista_param = self.lista_param_result()
            lista_param1 = self.lista_param_result1()
            lista_param2 = self.lista_param_result2()

            espg = self.ESPG

            # acessa layer do CAR (limites de propriedades)
            dir_layer0 = 'C:\\Users\\thomaz.costa\\Documents\\AProSEG_Pastagem\\BaseDados\CAR\\AREA_IMOVEL_1.shp' 
            vlayer0 = QgsVectorLayer(dir_layer0, "propriedades", "ogr")
            if not vlayer0.isValid():
                print("Layer failed to load!")
            # else:
            #     QgsProject.instance().addMapLayer(vlayer)


             # acessa layer de Municipios
            dir_layer = 'C:/Users/thomaz.costa/Documents/AProSEG_Pastagem/BaseDados/IBGE/MG_Municipios_2022.shp'

            vlayer = QgsVectorLayer(dir_layer, "MG_Municipios_2022", "ogr")
            if not vlayer.isValid():
                print("Layer failed to load!")
            # else:
            #     QgsProject.instance().addMapLayer(vlayer)

              # direcionando para o dir da zona para selecionar o DEM
            pasta = r'C:/Users/thomaz.costa/Documents/AProSEG_Pastagem/watershade_z'+str(self.zona)+'utm/Relevo/'
            file = 'NasaDEM_MG-1_Z'+str(self.zona)+'_utm.tif'

            # acessa DEM da zona
            dir_layer2 = pasta + file
            rlayer = QgsRasterLayer(dir_layer2, "NasaDEM")
            if not rlayer.isValid():
                print("Layer failed to load!")
            # else:
            #     QgsProject.instance().addMapLayer(rlayer)

             # acesso ao municipio pela tabela de atributos do layer de Municipios de MG
            atributos = vlayer.getFeatures()
            nomeCampo = 'NM_MUN'

            indiceCampo = vlayer.fields().indexOf(nomeCampo)

            munic = self.munic

            for atributo in atributos:
                munics = atributo.attributes()[indiceCampo]

                if munic in munics:
                    
                    #saida = 'D:/Usuarios/AProSEG_Pastagem/'+ munic + '.shp'
                    
                    # gera o municipio.shp
                    temporario = processing.run("native:extractbyattribute",
                                {'INPUT': vlayer,
                                    'FIELD': nomeCampo,
                                    'OPERATOR': 0,
                                    'VALUE': munic,
                                    'OUTPUT': 'memory:'})
                    

                    # Recorta layer propriedades (CAR)
                    saida1 = 'C:/Users/thomaz.costa/Documents/AProSEG_Pastagem/propried_' + munic + '.shp'

                    processing.run("native:clip", {'INPUT':vlayer0,\
                    'OVERLAY':temporario['OUTPUT'], 'OUTPUT':saida1})

                    #add output to the qgis interface
                    # iface.addVectorLayer(saida1, '', 'org')

                    vlayer_car = QgsVectorLayer(saida1, "propried", "ogr")
                    if not vlayer.isValid():
                        print("Layer failed to load!")
                    else:
                        QgsProject.instance().addMapLayer(vlayer_car)

                    # --------------------------------------------------------------
                    # criando arquivo de saida para o grass
                    fnm_input = pasta + file
                    fnm_output = pasta + 'saida.tif'

                    # abrir arquivo entrada em modo leitura (parametro 0)
                    rst_input = gdal.Open(fnm_input, 0)

                    # carregar a banda 1 da camada de entrada para matriz numpy:
                    # matriz = rst_input.GetRasterBand(1).ReadAsArray()

                    # Obter metadados da camada de entrada e criar camada de saída
                    # carregar driver para GeoTiff
                    driver_tiff = gdal.GetDriverByName('GTiff')

                    # criar raster de saída com metadados da camada de entrada
                    x = rst_input.RasterXSize
                    y = rst_input.RasterYSize

                    # camada raster de saída
                    rst_out = driver_tiff.Create(fnm_output, xsize=x, ysize=y,\
                    bands=1, eType=gdal.GDT_Float32)

                    # configurar geotransformaçao com base na camada de entrada
                    rst_out.SetGeoTransform(rst_input.GetGeoTransform())

                    # obter o tamanho da celula
                    cellsize = np.abs(rst_input.GetGeoTransform()[1])

                    # configurar projecao com base na camada de entrada
                    rst_out.SetProjection(rst_input.GetProjection())

                    # ler banda 1 da camada de saida
                    bnd1 = rst_out.GetRasterBand(1).ReadAsArray()

                    # EXPORTAR CAMADA DE SAIDA
                    #sobrescrever a banda 1 do raster de saida
                    rst_out.GetRasterBand(1).WriteArray(bnd1)

                    # fechar a camada
                    rst_out = None
                    # --------------------------------------------------------------  
                
                    saida2 = 'C:/Users/thomaz.costa/Documents/AProSEG_Pastagem/Dem_' + munic + '.tif'

                    # recorta o DEM pelo limite da carta
                    processing.run("gdal:cliprasterbymasklayer",
                                {'INPUT': rlayer,
                                    'MASK': temporario['OUTPUT'],
                                    'SOURCE_CRS': 'EPSG:'+str(self.zona)+'-SIRGAS 2000/UTM Zone'+str(self.zona)+'S',
                                    'TARGET_CRS': 'EPSG:'+str(self.zona)+'-SIRGAS 2000/UTM Zone'+str(self.zona)+'S',
                                    'TARGET_EXTENT': None,
                                    'NODATA': 0,
                                    'ALPHA_BAND': False,
                                    'CROP_TO_CUTLINE': True,
                                    'KEEP_RESOLUTION': False,
                                    'SET_RESOLUTION': False,
                                    'X_RESOLUTION': x,
                                    'Y_RESOLUTION': y,
                                    'MULTITHREADING': False,
                                    'OPTIONS': '',
                                    'DATA_TYPE': 0,
                                    'EXTRA': '',
                                    'OUTPUT': saida2})
                    
                    #  # carregando o resultado em tela
                    # iface.addRasterLayer(saida2)
                    
                    saida3 = 'C:/Users/thomaz.costa/Documents/AProSEG_Pastagem/Slope_' + munic + '.tif'
                    
                    # calcula declividade %
                    processing.run("grass7:r.slope.aspect", {
                                    'elevation': saida2,
                                    'format':1,
                                    'precision':0,
                                    '-a':True,
                                    '-e':False,
                                    '-n':False,
                                    'zscale':1,
                                    'min_slope':0,
                                    'slope': saida3,
                                    'GRASS_REGION_PARAMETER':None,'GRASS_REGION_CELLSIZE_PARAMETER':0,
                                    'GRASS_RASTER_FORMAT_OPT':'',
                                    'GRASS_RASTER_FORMAT_META':''})
                    
                    #  # carregando o resultado em tela
                    # iface.addRasterLayer(saida3)

                    saida4 = 'C:/Users/thomaz.costa/Documents/AProSEG_Pastagem/ClasSlope_' + munic + '.tif'

                    # classes de declividade pela a escolha do usuario
                    processing.run("native:reclassifybytable", {
                    'INPUT_RASTER':saida3,
                    'RASTER_BAND':1,
                    'TABLE': lista_param,
                    'NO_DATA':0,
                    'RANGE_BOUNDARIES':1,
                    'NODATA_FOR_MISSING':False,
                    'DATA_TYPE':5,
                    'OUTPUT': saida4
                    })

                    # # carregando o resultado em tela
                    # iface.addRasterLayer(saida4)

            #-------------------------------------------------------
            #-------------------------------------------------------
            # PROCESSA LAYER DEGRADACAO PASTAGENS DA UFG

            pasta = 'C:/Users/thomaz.costa/Documents/AProSEG_Pastagem/BaseDados/mg_pasture_quality_col7_s100_year=2021/'
            file = 'Pastagem_MapBiomas_2022.tif'

            # acessa Pastagem da UFG da zona
            dir_layer2 = pasta + file
            rlayer = QgsRasterLayer(dir_layer2, "Pastagem_MapBiomas")
            if not rlayer.isValid():
                print("Layer failed to load!")

            # QgsProject.instance().addMapLayer(rlayer)

            # acesso as cartas pela tabela de atributos do layer de articulaçoes do IBGE

            saida6 = 'C:/Users/thomaz.costa/Documents/AProSEG_Pastagem/Pastagem_' + munic + '.tif'
        
            # recorta o DEM pelo limite da carta
            processing.run("gdal:cliprasterbymasklayer",
                        {'INPUT': rlayer,
                            'MASK': temporario['OUTPUT'],
                            'SOURCE_CRS': None,
                            'TARGET_CRS': 'EPSG:'+str(self.zona)+'-SIRGAS 2000/UTM Zone'+str(self.zona)+'S',
                            'TARGET_EXTENT': None,
                            'NODATA': 0,
                            'ALPHA_BAND': False,
                            'CROP_TO_CUTLINE': True,
                            'KEEP_RESOLUTION': False,
                            'SET_RESOLUTION': False,
                            'X_RESOLUTION': 30,
                            'Y_RESOLUTION': 30,
                            'MULTITHREADING': False,
                            'OPTIONS': '',
                            'DATA_TYPE': 0,
                            'EXTRA': '',
                            'OUTPUT': saida6})
            
            #  # carregando o resultado em tela
            # iface.addRasterLayer(saida6)

            saida7 = 'C:/Users/thomaz.costa/Documents/AProSEG_Pastagem/ClasPast_' + munic + '.tif'

            # classes de degradacao pastagem pela escolha do usuario
            processing.run("native:reclassifybytable", {
                'INPUT_RASTER': saida6,
                'RASTER_BAND': 1,
                'TABLE': lista_param1,
                'NO_DATA': 0,
                'RANGE_BOUNDARIES': 1,
                'NODATA_FOR_MISSING': False,
                'DATA_TYPE': 5,
                'OUTPUT': saida7
            })

            # # carregando o resultado em tela
            # iface.addRasterLayer(saida7)

            # ----------------------------------------------------
            # ----------------------------------------------------
            # PROCESSA LAYER APTIDAO AGRICOLA do CNPS

            pasta = 'C:/Users/thomaz.costa/Documents/AProSEG_Pastagem/BaseDados/Solos/'
            file = 'pedoecol_mg.tif'

            # acessa pedoecol da zona
            dir_layer2 = pasta + file
            rlayer = QgsRasterLayer(dir_layer2, "pedoecol_mg")
            if not rlayer.isValid():
                print("Layer failed to load!")

            # QgsProject.instance().addMapLayer(rlayer)

            # acesso as cartas pela tabela de atributos do layer de articulaçoes do IBGE (temporario)

            saida6 = 'C:/Users/thomaz.costa/Documents/AProSEG_Pastagem/AptAgric_' + munic + '.tif'

            # recorta pedoecol_mg do CNPS pelo limite da carta
            processing.run("gdal:cliprasterbymasklayer",
                        {'INPUT': rlayer,
                            'MASK': temporario['OUTPUT'],
                            'SOURCE_CRS': 'EPSG:4674 - SIRGAS 2000',
                            'TARGET_CRS': 'EPSG:'+str(self.zona)+'-SIRGAS 2000/UTM Zone'+str(self.zona)+'S',
                            'TARGET_EXTENT': None,
                            'NODATA': 0,
                            'ALPHA_BAND': False,
                            'CROP_TO_CUTLINE': True,
                            'KEEP_RESOLUTION': False,
                            'SET_RESOLUTION': False,
                            'X_RESOLUTION': 30,
                            'Y_RESOLUTION': 30,
                            'MULTITHREADING': False,
                            'OPTIONS': '',
                            'DATA_TYPE': 0,
                            'EXTRA': '',
                            'OUTPUT': saida6})
            
            #  # carregando o resultado em tela
            # iface.addRasterLayer(saida6)

            saida8 = 'C:/Users/thomaz.costa/Documents/AProSEG_Pastagem/ClasAptAgric_' + munic + '.tif'

            # classes de aptidao agricola pela a escolha do usuario
            processing.run("native:reclassifybytable", {
                'INPUT_RASTER': saida6,
                'RASTER_BAND': 1,
                'TABLE': lista_param2,
                'NO_DATA':0,
                'RANGE_BOUNDARIES':1,
                'NODATA_FOR_MISSING':False,
                'DATA_TYPE':5,
                'OUTPUT': saida8
            })

            # # carregando o resultado em tela
            # iface.addRasterLayer(saida8)

            #-------------------------------------------------------
            #-------------------------------------------------------
            # OVERLAY (BOOLEANO)

            # ClasDecliv
            saida4 = 'C:/Users/thomaz.costa/Documents/AProSEG_Pastagem/ClasSlope_' + munic + '.tif'
            
            # DegrPast
            saida7 = 'C:/Users/thomaz.costa/Documents/AProSEG_Pastagem/ClasPast_' + munic + '.tif'
            
            # AptAgric
            # saida7 em aptagric é saida8 aqui
            saida8 = 'C:/Users/thomaz.costa/Documents/AProSEG_Pastagem/ClasAptAgric_' + munic + '.tif'

            # Resultado Final (seleção de áreas para agricultura)
            saida9 = 'C:/Users/thomaz.costa/Documents/AProSEG_Pastagem/SelectAgric_' + munic + '.tif'

            #  Overlay (booleano) ClasDecliv, DegrPast, AptAgric
            processing.run("native:rasterbooleanand", {
                'INPUT': [saida4, saida7, saida8],
                'REF_LAYER': saida4,
                'NODATA_AS_FALSE': False,
                'NO_DATA': 0,
                'DATA_TYPE': 1,
                'OUTPUT': saida9})

            # # carregando o resultado em tela
            # iface.addRasterLayer(saida9)

            # Resultado Final (seleção de áreas para agricultura)
            saida10 = 'C:/Users/thomaz.costa/Documents/AProSEG_Pastagem/Area_SelectAgric_' + munic + '.tif'

            # Classifica por limite de área (ha)
            processing.run(
            "grass7:r.reclass.area",
            {'input': saida9,
            'value':self.area_min,
            'mode':1,
            'method':0,
            '-c':False,
            '-d':False,
            'output':saida10,
            'GRASS_REGION_PARAMETER':None,
            'GRASS_REGION_CELLSIZE_PARAMETER':0,
            'GRASS_RASTER_FORMAT_OPT':'',
            'GRASS_RASTER_FORMAT_META':''})
            
             # carregando o resultado em tela
            iface.addRasterLayer(saida10)

            pass
